version: 2.1

jobs:
  grade:
    docker:
      - image: continuumio/miniconda3:4.5.11

    working_directory: /tmp/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --progress-bar off ipython ipywidgets
            pip install --progress-bar off https://github.com/nteract/papermill/archive/89a43a1bade7d9ba71b47a8a18cfc4d0b82e902a.zip
            pip install --progress-bar off https://github.com/earthlab/grading-workflow-experiments/archive/master.zip

      - run:
          name: "Prepare directories"
          command: |
            mkdir -p notebooks/week1
            mkdir -p notebooks/week3
            
      - run:
          name: Execute week1/homework.ipynb
          command: |
            papermill --cwd week1 week1/homework.ipynb homework-graded.ipynb
            jupyter nbconvert --to html --stdout week1/homework-graded.ipynb > notebooks/week1/homework.html
      - run:
          name: Execute week3/homework.ipynb
          command: |
            papermill --cwd week3 week3/homework.ipynb homework-graded.ipynb
            jupyter nbconvert --to html --stdout week3/homework-graded.ipynb > notebooks/week3/homework.html
      
      - store_artifacts:
          path: /tmp/repo/notebooks
          destination: notebooks

workflows:
  version: 2
  grade_me:
    jobs:
      - grade